module.exports = {
  products: [
    {
      _id: "1",
      ref: "pizza_tradicional",
      category: "Tradicional",
      sabor: "Pizza Bacon",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "1-pizza_de_bacon_hero_min-350x350.jpeg",
    },
    {
      _id: "2",
      ref: "pizza_tradicional",
      category: "Tradicional",
      sabor: "Pizza Calabresa",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "pizza-calabresa_min-350x350.jpg",
    },
    {
      _id: "3",
      ref: "pizza_tradicional",
      category: "Tradicional",
      sabor: "Pizza Marguerita",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "pizza-marguerita_min-350x350.jpg",
    },
    {
      _id: "4",
      ref: "Pizza Milho Verde",
      category: "Tradicional",
      sabor: "Pizza Milho Verde",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Banana",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "milho_IMG_1158-350x350.jpg",
    },
    {
      _id: "5",
      ref: "pizza_tradicional",
      category: "Tradicional",
      sabor: "Pizza Muçarela",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "pizza-mucarela_min-350x350.jpg",
    },
    {
      _id: "6",
      ref: "pizza_tradicional",
      category: "Tradicional",
      sabor: "Pizza Napolitana",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "pizza-napolitana_min-350x350.jpg",
    },
    {
      _id: "7",
      ref: "pizza_tradicional",
      category: "Tradicional",
      sabor: "Pizza Presunto",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "pizza-presunto_min-350x350.jpg",
    },
    {
      _id: "8",
      ref: "pizza_tradicional",
      category: "Tradicional",
      sabor: "Pizza Rúcula",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "pizza-rucula_©meurancho_min-350x350.jpg",
    },

    {
      _id: "26",
      ref: "pizza_especial",
      category: "Especial",
      sabor: "Pizza Bella",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "Banana26.jpg",
    },
    {
      _id: "27",
      ref: "pizza_especial",
      category: "Especial",
      sabor: "Pizza Carne de Sol",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "englaise.jpg",
    },
    {
      _id: "28",
      ref: "pizza_especial",
      category: "Especial",
      sabor: "Pizza Cinco Carnes",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "Banana28.jpg",
    },
    {
      _id: "29",
      ref: "pizza_especial",
      category: "Especial",
      sabor: "Especial",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "Banana2.jpg",
    },
    {
      _id: "31",
      ref: "pizza_especial",
      category: "Especial",
      sabor: "Pizza Frango com Palmito à Bolonhesa",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "Banana31.jpg",
    },
    {
      _id: "31",
      ref: "pizza_especial",
      category: "Especial",
      sabor: "Pizza Frango com Palmito e Catupiry",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "Banana31.jpg",
    },
    {
      _id: "33",
      ref: "pizza_especial",
      category: "Especial",
      sabor: "Pizza Firenze",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "Banana33.jpg",
    },
    {
      _id: "34",
      ref: "pizza_especial",
      category: "Especial",
      sabor: "Pizza Grand Prix",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "Banana34.jpg",
    },
    {
      _id: "35",
      ref: "pizza_especial",
      category: "Especial",
      sabor: "Pizza Peito de Peru",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "Banana35.jpg",
    },
    {
      _id: "36",
      ref: "pizza_especial",
      category: "Especial",
      sabor: "Pizza Pizzaiollo",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "Banana36.jpg",
    },
    {
      _id: "37",
      ref: "pizza_especial",
      category: "Especial",
      sabor: "Pizza Romana",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "Banana37.jpg",
    },
    {
      _id: "38",
      ref: "pizza_especial",
      category: "Especial",
      sabor: "Pizza Chicken & Bacon",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "Banana38.jpg",
    },
    {
      _id: "39",
      ref: "pizza_especial",
      category: "Especial",
      sabor: "Pizza Tomate Seco",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "Banana39.jpg",
    },

    {
      _id: "40",
      ref: "pizza_doce",
      category: "Doce",
      sabor: "Pizza Banana",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "pizza-banana3-350x350.jpg",
    },
    {
      _id: "41",
      ref: "pizza_doce",
      category: "Doce",
      sabor: "Pizza Banana com Chocolate",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "pizza-chocolate-banana-350x350.jpg",
    },
    {
      _id: "42",
      ref: "pizza_doce",
      category: "Doce",
      sabor: "Pizza Brigadeiro",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "brigadeiro-cereja-350x350.jpg",
    },
    {
      _id: "43",
      ref: "pizza_doce",
      category: "Doce",
      sabor: "Pizza Confetes de Chocolate",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "pizzzaconfeiteschocolate.png",
    },
    {
      _id: "44",
      ref: "pizza_doce",
      category: "Doce",
      sabor: "Pizza Prestígio",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "prestigio-350x350.jpg",
    },
    {
      _id: "46",
      ref: "pizza_doce",
      category: "Doce",
      sabor: "Pizza Chocolate com Morango",
      price: 24.99,
      ingredients: [
        {
          _id: "1",
          ingrdientName: "Bacon",
          image: "bacon.png",
        },
        {
          _id: "2",
          ingrdientName: "Mussarela",
          image: "mucarela.png",
        },
        {
          _id: "3",
          ingrdientName: "Orégano",
          image: "oregano.png",
        },
        {
          _id: "4",
          ingrdientName: "Ham",
          image: "ham.png",
        },
        {
          _id: "5",
          ingrdientName: "Tomato Sauce",
          image: "tomate.png",
        },
        {
          _id: "6",
          ingrdientName: "Fatias de Tomate",
          image: "tomate-fatiado.png",
        },
      ],
      bgImage:"url(http://192.168.1.104:3000/assets/ingredients/ingredientbg.jpg",
      image: "chocolate-morango-350x350.jpg",
    },
  ],
};
