export const pizzaTradicional = [
  {
    id: 1,
    ref: "pizza_tradicional",
    category: 0,
    sabor: "Pizza Bacon",
    price: "24,99",
    ingredient: "Muçarela;Bacon;Fatias de Tomate;Orégano",
    image: "1-pizza_de_bacon_hero_min-350x350.jpeg",
  },
  {
    id: 2,
    ref: "pizza_tradicional",
    category: 0,
    sabor: "Pizza Calabresa",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "pizza-calabresa_min-350x350.jpg",
  },
  {
    id: 3,
    ref: "pizza_tradicional",
    category: 0,
    sabor: "Pizza Marguerita",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "pizza-marguerita_min-350x350.jpg",
  },
  {
    id: 4,
    ref: "Pizza Milho Verde",
    category: 0,
    sabor: "Pizza Milho Verde",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "milho_IMG_1158-350x350.jpg",
  },
  {
    id: 5,
    ref: "pizza_tradicional",
    category: 0,
    sabor: "Pizza Muçarela",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "pizza-mucarela_min-350x350.jpg",
  },
  {
    id: 6,
    ref: "pizza_tradicional",
    category: 0,
    sabor: "Pizza Napolitana",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "pizza-napolitana_min-350x350.jpg",
  },
  {
    id: 7,
    ref: "pizza_tradicional",
    category: 0,
    sabor: "Pizza Presunto",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "pizza-presunto_min-350x350.jpg",
  },
  {
    id: 8,
    ref: "pizza_tradicional",
    category: 0,
    sabor: "Pizza Rúcula",
    price: "24,99",
    ingredient:
      "Molho de tomate;Muçarela;Rúcala;Fatias de Tomate;Alho Desidratado;Orégano",
    image: "pizza-rucula_©meurancho_min-350x350.jpg",
  },
];

export const pizzaEspecial = [
  {
    id: 26,
    ref: "pizza_especial",
    category: 1,
    sabor: "Pizza Bella",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "Banana26.jpg",
  },
  {
    id: 27,
    ref: "pizza_especial",
    category: 1,
    sabor: "Pizza Carne de Sol",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "englaise.jpg",
  },
  {
    id: 28,
    ref: "pizza_especial",
    category: 1,
    sabor: "Pizza Cinco Carnes",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "Banana28.jpg",
  },
  {
    id: 29,
    ref: "pizza_especial",
    category: 1,
    sabor: "Pizza Especial",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "Banana2.jpg",
  },
  {
    id: 31,
    ref: "pizza_especial",
    category: 1,
    sabor: "Pizza Frango com Palmito à Bolonhesa",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "Banana31.jpg",
  },
  {
    id: 31,
    ref: "pizza_especial",
    category: 1,
    sabor: "Pizza Frango com Palmito e Catupiry",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "Banana31.jpg",
  },
  {
    id: 33,
    ref: "pizza_especial",
    category: 1,
    sabor: "Pizza Firenze",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "Banana33.jpg",
  },
  {
    id: 34,
    ref: "pizza_especial",
    category: 1,
    sabor: "Pizza Grand Prix",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "Banana34.jpg",
  },
  {
    id: 35,
    ref: "pizza_especial",
    category: 1,
    sabor: "Pizza Peito de Peru",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "Banana35.jpg",
  },
  {
    id: 36,
    ref: "pizza_especial",
    category: 1,
    sabor: "Pizza Pizzaiollo",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "Banana36.jpg",
  },
  {
    id: 37,
    ref: "pizza_especial",
    category: 1,
    sabor: "Pizza Romana",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "Banana37.jpg",
  },
  {
    id: 38,
    ref: "pizza_especial",
    category: 1,
    sabor: "Pizza Chicken & Bacon",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "Banana38.jpg",
  },
  {
    id: 39,
    ref: "pizza_especial",
    category: 1,
    sabor: "Pizza Tomate Seco",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "Banana39.jpg",
  },
];

export const pizzaDoce = [
  {
    id: 1,
    ref: "pizza_doce",
    category: 2,
    sabor: "Pizza Banana",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "pizza-banana3-350x350.jpg",
  },
  {
    id: 2,
    ref: "pizza_doce",
    category: 2,
    sabor: "Pizza Banana com Chocolate",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "pizza-chocolate-banana-350x350.jpg",
  },
  {
    id: 3,
    ref: "pizza_doce",
    category: 2,
    sabor: "Pizza Brigadeiro",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "brigadeiro-cereja-350x350.jpg",
  },
  {
    id: 4,
    ref: "pizza_doce",
    category: 2,
    sabor: "Pizza Confetes de Chocolate",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "pizzzaconfeiteschocolate.png",
  },
  {
    id: 5,
    ref: "pizza_doce",
    category: 2,
    sabor: "Pizza Prestígio",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "prestigio-350x350.jpg",
  },
  {
    id: 6,
    ref: "pizza_doce",
    category: 2,
    sabor: "Pizza Chocolate com Morango",
    price: "24,99",
    ingredient: "Frango;Mussarela;Cheddar;Azeitona preta;Cebola",
    image: "chocolate-morango-350x350.jpg",
  },
];

export const list = [pizzaTradicional, pizzaEspecial, pizzaDoce];
export const allpizza = [...pizzaTradicional, ...pizzaEspecial, ...pizzaDoce];
